// <auto-generated />
namespace Onyx.Authorization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class userprofiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userprofiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201501212210160_userprofiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
